export default {
   NEW_UI_COLORS: {
      PRIMARY: '#57BE82',

      INPUT: '#FFFFFF',
      INPUT_PLACEHOLDER: '#FFFFFF55',
      INPUT_BORDER: '#404040',
      INPUT_ICON: '#FFFFFF',

      SUBMIT: '#1F2229',
      SUBMIT_DISABLE: '#BEBEBE',
      SUBMIT_TEXT: '#FFFFFF',

      TRANSPARENT_BUTTON_TEXT: '#969696',

      SELECTED: '#248047',

      BACKGROUND: '#1A1B1E',
      TABBAR_BACKGROUND: '#0D0D0E',

      TITLE: '#FFFFFF',
      TEXT_PRIMARY: '#57BE82',
      TEXT_SECONDARY: '#8289AB',
      TEXT_ERROR: '#AD2145',
      TEXT_DIVIDER: '#FFFFFF',
   },
   NEW_UI_FONTS: {
      PRIMARY: 'Poppins',
   },
};
